Syncing recent dotfiles modifications with repository

diff --git a/bashrc.d/builtin_extensions b/bashrc.d/builtin_extensions
--- a/bashrc.d/builtin_extensions
+++ b/bashrc.d/builtin_extensions
@@ -1,293 +1,298 @@
 #!/usr/bin/env bash
 #
-## Extension to builtins and other helpful stuff in pure bash
-###
+# builtin extensions (and other useful functions)
 
 
-###
-## cdls - cd into a directory and list it's contents
-##
-## usage: cdls [ls-options ...] directory
-##
-## @ls-options : option(s) for ls
-## @directory: the name of the directory
-###
+# shellcheck disable=SC1091
+if [[ -f ${BASH_SOURCE[0]%/*}/libmsg ]]
+then
+    source -- "${BASH_SOURCE[0]%/*}/libmsg"
+fi
+
+
+#######################################
+# fork - fork a command
+#
+# usage: fork command
+#######################################
+fork()
+{
+    if (( $# ))
+    then
+        (exec -- "$@" &) 
+    fi
+} 0</dev/null 1>/dev/null
+
+
+############################################################################
+# cdls - cd into a directory and list it's contents
+#
+# usage: cdls [ls-options ...] directory
+#
+# @ls-options : option(s) for ls
+# @directory: the name of the directory
+#######################################
 cdls()
 {
-  if (( $# )); then
-    cd -- "${!#}" && ls "${@:1:($# ? ($# - 1) : 0)}"
-  else
-    printf 1>&2 'usage: %s [ls_options] [--] directory\n' "${FUNCNAME}"
-    return 2
-  fi
+    if (( $# ))
+    then
+        cd -- "${!#}" && ls "${@:1:($# ? ($# - 1) : 0)}"
+    else
+        msg::err "${FUNCNAME[0]}" 'usage' "${FUNCNAME[0]} [ls-options] directory"
+        return 2
+    fi
 }
 
 
-###
-## mkcd - make a directory and cd into it
-##
-## usage: mkcd [mkdir-options ...] directory
-##
-## @mkdir-options : option(s) for mkdir
-## @directory: the name of the directory
-###
+#######################################
+# mkcd - make a directory and cd into it
+#
+# usage: mkcd [mkdir-options ...] directory
+#
+# @mkdir-options : option(s) for mkdir
+# @directory: the name of the directory
+#######################################
 mkcd()
 {
-  if (( $# )); then
-    mkdir "$@" && cd -- "${!#}"
-  else
-    printf 1>&2 'usage: %s [mkdir_options] [--] directory\n' "${FUNCNAME}"
-    return 2
-  fi
+    if (( $# ))
+    then
+        mkdir "$@" && cd -- "${!#}" || return
+    else
+        msg::err "${FUNCNAME[0]}" 'usage' "${FUNCNAME[0]} [mkdir-options] directory"
+        return 2
+    fi
 }
 
 
-###
-## lswhich - print a long listing of each command
-##
-## usage: lstype [name ...]
-##
-## @name: command name(s) to list
-###
+#######################################
+# lswhich - print a long listing of each command
+#
+# usage: lstype [name] ...
+#
+# @name: command name(s) to list
+#######################################
 lswhich()
 {
-  local REPLY
-  for _; do
-    while read -r REPLY; do
-      ls -l "${REPLY}"
-    done < <(type -ap "$_")
-  done
+    local IFS REPLY || return
+
+    while (( $# ))
+    do
+        while IFS='' read -r -a REPLY
+        do
+            ls -l "${REPLY[@]}"
+        done < <(type -ap "$1")
+        shift
+    done
 }
 
 
-###
-## errmsg - print an error message
-##
-## usage: errmsg [name ...] error
-##
-## @name: program(s), function(s), or value(s) to prepend
-## @error: the error message to print
-##
-## Return: the exit status of the command before this function
-###
-errmsg()
+#######################################
+# putslist - print a comma-separated list
+#
+# usage: putslist value ...
+#######################################
+putslist()
 {
-  trap -- "$(
-    printf "%s\nreturn $?" "$(
-      : "$(trap -p RETURN)"
-      printf '%s' "${_:-trap - RETURN}"
-  )")" RETURN
-  if (( $# > 0 )); then
-    if (( $# > 1 )); then
-      printf '%s: ' "${@:1:($# - 1)}"
+    local IFS="${IFS:-, }" && local MAPFILE || return
+
+    if ! (( $# ))
+    then
+        msg::err "${FUNCNAME[0]}" 'usage' "${FUNCNAME[0]} [value] ..."
+        return 2
     fi
-    printf '%s\n' "${!#}"
-  fi 1>&2
+
+    mapfile -d "${IFS:0:1}" MAPFILE <<<"$*"
+
+    MAPFILE[-1]="${MAPFILE[-1]%?}"
+
+    IFS="${IFS:1}"
+
+    if [[ ${#IFS} -gt 1 ]]
+    then
+        "${FUNCNAME[0]}" "${MAPFILE[@]}"
+    else
+        printf '%s' "${MAPFILE[*]}"$'\n'
+    fi
 }
 
 
-###
-## up - cd upward
-##
-## usage: up [depth]
-##
-## @depth : The number of levels to cd up
-###
+#######################################
+# abspath - determine absolute paths
+#
+# usage: abspath PATHNAME ...
+#######################################
+abspath()
+{
+    local pathname IFS REPLY || return
+
+    if ! (( $# ))
+    then
+        msg::err "${FUNCNAME[0]}" 'usage' "${FUNCNAME[0]} pathname ..."
+    fi
+
+    for pathname
+    do
+        pathname="${pathname%"${pathname##*[^/]}"}"
+
+        pathname="${pathname/%[^\/]"${pathname:1}"/"./${pathname}"}"
+
+        if [[ -d ${pathname:=/} ]]
+        then
+            if wait "$!"
+            then
+                IFS='' read -r -d '' REPLY
+
+                printf '%q\n' "${REPLY%?}"
+
+            fi < <(CDPATH='' cd -- "${pathname}" && pwd && printf '\0')
+
+        elif wait "$!"
+        then
+            IFS='' read -r -d '' REPLY
+
+            printf '%q\n' "${REPLY%?}/${pathname##*/}"
+
+        fi < <(CDPATH='' cd -- "${pathname%/*}/" && pwd && printf '\0')
+        shift
+    done
+}
+
+
+#######################################
+# up - ascend through a directory tree
+#
+# usage: up [DEPTH]
+#
+# @DEPTH : number of levels to ascend
+#######################################
 up()
 {
-  if (( $# > 1 )); then
-    printf 1>&2 'usage: %s [depth]\n' "${FUNCNAME}"
-    return 2
-  elif [[ ${1:-1} -lt 0 || $1 = *[^[:digit:]]* ]]; then
-    errmsg "${FUNCNAME}" 'depth must be a non-negative integer'
-    return 1
-  elif [[ ${1:-1} -gt 0 ]]; then
-    cd -- "$(for ((__up = ${1:-1}; __up > 0; __up -= 1)); do printf ../; done)"
-  fi
+    if [[ $# -eq 0 ]]
+    then
+        cd ..
+        return
+    fi
+
+    if [[ $# -gt 1 ]]
+    then
+        printf 1>&2 '%s: usage: %s [depth]\n' "${FUNCNAME[0]}" "${FUNCNAME[0]}"
+        return 2
+    fi
+
+    if (( ($1) < 1 ))
+    then
+        printf 1>&2 '%s: %s: depth must be a positive integer\n' "${FUNCNAME[0]}" "$1"
+        return 1
+    fi
+
+    cd "$(
+    PWD="${PWD//[^/]}"
+    eval printf %.s../ \{1.."$(( ${#PWD} < $1 ? ${#PWD} : $1 ))"\}
+    )" || return
 }
 
 
-###
-## add-alias - adds an alias to bash aliases file 
-##
-## usage: addalias name[=value] ...
-##
-## @name: the name of an alias
-## @value: optionally, a value to assign to name
-##
-## Return: 2 if called with the wrong number of arguments,
-## 1 if name is invalid or value is not given and name does not exist,
-## 0 otherwise.
-###
+#######################################
+# add-alias - adds an alias to bash aliases file 
+#
+# usage: addalias NAME[=VALUE] ...
+#
+# @NAME: the name of an alias
+# @VALUE: optionally, a value to assign to name
+#
+# Return: 2 if called with the wrong number of arguments,
+# 1 if name is invalid or value is not given and name does not exist,
+# 0 otherwise.
+#######################################
 addalias()
 {
-  local -
-  if [[ -n ${DEBUG+_} ]]; then
-    set -"${DEBUG_OPTS:-xv}"
-  fi
-  local OPTIND=1
-  local opt=''
-  local out=''
-  while getopts ':o:h' opt; do
-    case ${opt} in
-      o ) out="${OPTARG}"
-        ;;
-      h ) printf 'usage: %s [-o file] name[=value] ...\n' "${FUNCNAME}"
-        ;;&
-      : ) errmsg "${FUNCNAME}" "${OPTARG}" 'option requires an argument'
-        ;;&
-      \?) errmsg "${FUNCNAME}" "${OPTARG}" 'invalid option'
-        ;;&
-      * ) return 2
-        ;;
-    esac
-  done
-  shift "$(( OPTIND - 1 ))"
-  while (( $# )); do
-    alias -- "$1"
-    case "$1" in
-      *=*) alias -- "${1%%=*}" ;;
-    esac
-    shift
-  done >> "${out:-${BASH_ALIASES_FILE:-${HOME}/.bash_aliases}}"
+    local OPTARG
+    local OPTIND=1
+    local option
+    local output="${BASH_ALIASES_FILE:-${HOME-}/.bash_aliases}"
+
+    while getopts ':o:h' option
+    do
+        case "${option}" in
+            o ) output="${OPTARG}"
+                ;;
+            h ) msg::std "${FUNCNAME[0]}"  'usage: %s [-o file] name[=value] ...'
+                ;;&
+            : ) msg::err "${FUNCNAME[0]}" "-${OPTARG}" 'option requires an argument'
+                ;;&
+            \?) msg::err "${FUNCNAME[0]}" "-${OPTARG}" 'invalid option'
+                ;;&
+            * ) return 2
+        esac
+    done
+    shift "$((OPTIND - 1))"
+    for _
+    do
+        if [[ $_ == *=* ]]
+        then
+            alias -- "$_" "${_%%=*}"
+        else
+            alias -- "$_"
+        fi
+    done 1>> "${output}"
 }
 
 
-###
-## pushdtmp - make a temp directory and push it onto the directory stack
-##
-## usage: pushdtmp [template]
-##
-## @template: directory name template (must contain 3 or more consecutive X's)
-###
-pushdtmp()
+#######################################
+# pushtmp - make a temp directory and push it onto the directory stack
+#
+# usage: pushtmp [TEMPLATE]
+#
+# @TEMPLATE: directory name template (must contain 3 or more consecutive X's)
+#######################################
+pushtmp()
 {
-  local -
-  if [[ -n ${DEBUG+_} ]]; then
-    set -"${DEBUG_OPTS:-xv}"
-  fi
-  if (( $# > 1 )); then
-    errmsg "${FUNCNAME}" 'too many arguments'
-    printf 1>2 'usage: %s [template]\n' "${FUNCNAME}"
-    return 2
-  fi
-  if wait "$!"; then
-    pushd "$(< /dev/stdin)"
-  fi < <(mktemp -d --tmpdir -- "${1-tmp.XXXXXXXXXX}")
+    if (( $# > 1 ))
+    then
+        msg::err "${FUNCNAME[0]}" 'usage' "${FUNCNAME[0]} [template]"
+        return 2
+    fi
+    if wait "$!"
+    then
+        pushd -- "$(cat)"
+    fi < <(mktemp -d --tmpdir -- "${1:-${FUNCNAME[0]}-XXX}")
 }
 
 
-###
-## assign_by_ref - assign a value to a variable by reference
-##
-## usage: assign_by_ref name [value]
-##
-## @name: the name of a variable
-## @value: the value to assign
-##
-## Return: 1 if name is not a valid identifier or has a bad subscript,
-## 2 if called with the wrong number of arguments,
-## otherwise 0
-###
+#######################################
+# Assign a value to a variable by reference
+# Usage:
+#   assign_by_ref NAME [VALUE]
+# Globals:
+#   BASH_REMATCH
+# Arguments:
+#   NAME: variable name
+#   VALUE: value to assign
+# Return:
+#   1 if given an invalid identifier or a bad array subscript,
+#   2 if given the wrong number of arguments,
+#   0 otherwise
+#######################################
 assign_by_ref()
 {
-  local -
-  if [[ -n ${DEBUG+_} ]]; then
-    set -"${DEBUG_OPTS:-xv}"
-  fi
-  if (( $# != 2 )); then
-    errmsg "${FUNCNAME}" 'wrong number of arguments'
-    printf 1>&2 'usage: %s name value\n' "${FUNCNAME}"
-    return 2
-  fi
-  [[ $1 =~ ^([[:alpha:]_][[:alnum:]_]*)(\[(.*)])?$ ]]  ||
-    errmsg "${FUNCNAME}" "$1" 'not a valid identifier' ||
-    return 1
-  if [[ ${BASH_REMATCH[2]} = ?(\[*([[:blank:]])+([[:digit:]])*([[:blank:]])]) ]]
-  then
-    eval "$1"'=$2'
-  elif [[ ${!BASH_REMATCH[1]@a} = *A* ]]; then
-    eval "${BASH_REMATCH[1]}[${BASH_REMATCH[3]@Q}]"'=$2'
-  else
-    errmsg "${FUNCNAME}" "${BASH_REMATCH[1]}[${BASH_REMATCH[3]@Q}]" \
-      'bad array subscript'
-    return 1
-  fi
-}
-
-
-###
-## subrepl_function - make new functions from old ones
-##
-## usage: subrepl_function old-func new-func [pattern sub]
-###
-subrepl_function()
-{ 
-  local -
-  if [[ -n ${DEBUG+_} ]]; then
-    set -"${DEBUG_OPTS:-xv}"
-  fi
-  if (( $# !=2 && $# != 4 )); then
-    printf 1>&2 'usage: %s old-func new-func [pattern sub]\n' "${FUNCNAME}"
-    return 2
-  fi
-  if [[ ${FUNCNAME} = ${FUNCNAME[1]} ]]; then
-    trap -- "$(
-    : "$(trap -p RETURN)"
-      printf '%s\n' "${_:-trap - RETURN}"
-      : "$(declare -pf "$2")"
-      printf '%s\n' "${_//$3/"$4"}"
-    )" RETURN
-  elif declare -F -- "$1"; then
-    trap -- "$(
-      : "$(trap -p RETURN)"
-      printf '%s\n' "${_:-trap - RETURN}"
-      : "$(declare -pf "$1")"
-      printf '%s\n' "${_/"$1"/"$2"}"
-    )"$'\n'"${FUNCNAME}"' "$@"'$'\n''return' RETURN
-  fi 1>/dev/null
-}
-
-print_unicode () 
-{ 
-    trap "$(
-    : "$(trap -p ERR)"
-    printf '%s\n' "${_:-trap - ERR}"
-    : "$(trap -p RETURN)"
-    printf '%s\n' "${_:-trap - RETURN}"
-  )" RETURN;
-    trap - ERR;
-    if ! local chr end inc; then
-        printf '%q: %q: cannot create local vars\n' "${0##*/}" "${FUNCNAME}" 1>&2;
-        return 10;
-    fi;
-    if (( $# > 2 )); then
-        printf '%q: %q: too many arguments\n' "${0##*/}" "${FUNCNAME}" 1>&2;
-        return 1;
-    fi;
-    if (( $# < 2 )); then
-        printf '%q: %q: missing required arguments\n' "${0##*/}" "${FUNCNAME}" 1>&2;
-        printf '%q: usage: %q start end\n' "${FUNCNAME}" "${FUNCNAME}" 1>&2;
-        return 2;
-    fi;
-    if [[ $1 != +([[:xdigit:]]) ]]; then
-        printf '%q: %q: invalid starting character\n' "${0##*/}" "${FUNCNAME}" 1>&2;
-        printf '%q: usage: %q start end\n' "${FUNCNAME}" "${FUNCNAME}" 1>&2;
-        return 2;
-    fi;
-    if [[ $2 != +([[:xdigit:]]) ]]; then
-        printf '%q: %q: invalid ending character\n' "${0##*/}" "${FUNCNAME}" 1>&2;
-        printf '%q: usage: %q start end\n' "${FUNCNAME}" "${FUNCNAME}" 1>&2;
-        return 2;
-    fi;
-    chr=$(( 16#$1 ));
-    end=$(( 16#$2 ));
-    inc=$(( 16#$1 < 16#$2 ? 1 : -1 ));
-    while printf -v chr '%08x' "$(( chr ))";
-    printf '%b' "\\U${chr}";
-    (( 16#${chr} != end )); do
-        chr=$(( 16#${chr} + inc ));
-        printf '%s' "${sep:-", "}";
-    done;
-    echo
+    if (( $# != 2 ))
+    then
+        msg::err "${FUNCNAME[0]}" 'usage' "${FUNCNAME[0]} name value"
+        return 2
+    elif ! [[ $1 =~ ^([[:alpha:]_][[:alnum:]_]*)(\[(.*)])?$ ]]
+    then
+        msg::err "${FUNCNAME[0]}" "$1" 'not a valid identifier'
+        return 1
+    elif [[ -z ${BASH_REMATCH[2]} ]]
+    then
+        eval "$1"'=$2'
+    elif [[ ${!BASH_REMATCH[1]@a} == *A* ]]
+    then
+        eval "${BASH_REMATCH[1]}[${BASH_REMATCH[3]@Q}]"'=$2'
+    elif (( $((BASH_REMATCH[3])), 1 )) 2>/dev/null
+    then
+        eval "${BASH_REMATCH[1]}[$((BASH_REMATCH[3]))]"'=$2'
+    else
+        msg::err "${FUNCNAME[0]}" "${BASH_REMATCH[0]}" 'bad array subscript'
+    fi
 }
diff --git a/bashrc.d/holberton b/bashrc.d/holberton
--- a/bashrc.d/holberton
+++ b/bashrc.d/holberton
@@ -3,83 +3,73 @@
 ## aliases, functions and variables for Holberton
 ###
 
-alias gcc="gcc -std=c90 -Wall -Werror -Wextra -pedantic"
+alias gcc='gcc -Wall -Werror -Wextra -pedantic'
 
-
-
-
-
-
-
-export hb_project_dir='/home/pat/Documents/Holberton/Projects/holbertonschool-low_level_programming/0x10-variadic_functions'
-
-hb-project()
+hbtn-project()
 {
   local REPLY
   case $# in
     0)
-      if [[ -n ${hb_project_dir} ]]; then
-        cd -- "${hb_project_dir}"
+      if [[ -n ${hbtn_project} ]]; then
+        cd -- "${hbtn_project}" || unset -v hbtn_project
       else
-        printf 1>&2 '%q: project directory is not set\n' "${FUNCNAME}"
-        printf 1>&2 'Supply a directory name as an argument to set it\n'
-        return 1
+        printf 1>&2 '%q: project directory is not set\n' "${FUNCNAME[0]}"
+        printf 1>&2 'Supply a directory name to set it\n'
+        return 0
       fi
       ;;
     1)
-      if [[ -n ${hb_project_dir} ]]; then
+      if [[ -n ${hbtn_project} ]]; then
         read -r -p 'Change the active project directory? [Y/n] ' REPLY
         if [[ ${REPLY^} != Y* ]]; then
-          printf 'Abort.\n'
+          printf 'Aborting.\n'
           return 0
         fi
       fi
-      if __hb-project-set "$1"; then
-          printf 'Project directory set to %s\n' "${hb_project_dir@Q}"
+      if __hbtn-project-set "$1"; then
+          printf 'Project directory set to %q\n' "${hbtn_project}"
         return 0
       else
-        printf 'Refusing to set project directory\n'
+        printf 'Refusing to set project directory to %q\n' "$1"
         return 1
       fi
       ;;
     *)
-      printf 1>&2 '%q: too many arguments\n' "${FUNCNAME}"
-      printf 1>&2 'usage: %q [directory]\n'  "${FUNCNAME}"
+      printf 1>&2 '%q: too many arguments\n' "${FUNCNAME[0]}"
+      printf 1>&2 'usage: %q [directory]\n'  "${FUNCNAME[0]}"
       return 2
       ;;
   esac
 }
 
-__hb-project-set()
+__hbtn-project-set()
 {
-  local hb_project_dir                                            &&
-  hb_project_dir=$(CDPATH= cd -- "${1:-.}" && pwd -P && printf +) &&
-  hb_project_dir=${hb_project_dir%??}                             &&
-  sed -E -i '
-  /^export hb_project_dir=/{
-    : get
-    /\\$/{
+    local hbtn_project &&
+        hbtn_project="$(CDPATH='' cd -- "${1:-.}" && pwd && printf +)" &&
+        hbtn_project="${hbtn_project%??}" || return
+
+    # shellcheck disable=SC2016
+    sed -i -E '
+    /^export hbtn_project=/{
+      : old
+      /(^|[^\])(\\\\)*\\$/{
+        N
+        b old
+      }
+      z
+      : new
+      a export hbtn_project='"${hbtn_project@Q}"'
+      : cat
       N
-      b get
+      b cat
     }
-    z
-    : var
-    a export hb_project_dir='"'${hb_project_dir//\'/\'\\\'\'}'"'
-    : cat
-    n
-    b cat
-  }
-  $b var' "${BASH_SOURCE[0]}" && declare -gx hb_project_dir="${hb_project_dir}"  
+    $b new
+    ' "${BASH_SOURCE[0]}" && declare -gx hbtn_project="${hbtn_project}"
 }
 
 
-hb-gcc() 
-{
-  gcc "$@" "${1%%-*}-main.c" -o "${1%.c}"
-}
 
 
-hb-gcc-run() 
-{ 
-  gcc "$@" "${1%%-*}-main.c" -o "${1%.c}" && ./"${1%.c}"
-}
+
+
+export hbtn_project='/home/pat/Documents/Holberton/Projects/holbertonschool-low_level_programming/0x19-stacks_queues_lifo_fifo'
